# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c627c4bc78532264887f1cf460c9076cb92aa6b335dd0ffadd3827020e7a6d43fab528fdfe8adb38d56f9b6172ed81cf6de666ac92402901a75907e23f720bfc
  alchemy_api_key: 6a2eef4257aec2d8408db66a1126d06c35e9b1e3

test:
  secret_key_base: de7e03c82e251066c8adfe6a956b12d68ff1a54ec82a0d969ec5a1953a477f4025912e3eb6efc04cd0922ec6f0221379c91dac00e1b9d2a23beafece1049d004
  alchemy_api_key: 6a2eef4257aec2d8408db66a1126d06c35e9b1e3
  
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
